import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { GlobalNav } from "./components/global-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko" suppressHydrationWarning={true}>
            <body className={inter.className}>
                <div className="flex flex-col md:flex-row">
                    <GlobalNav />
                    {children}
                </div>
                <Toaster />
            </body>
        </html>
    );
}
